// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://queue.fal.run" | (string & {});
};

/**
 * StructuredPrompt
 */
export type BriaFiboVlmStructuredPrompt = {
  /**
   * Background Setting
   *
   * The background setting of the image to be generated.
   */
  background_setting?: string | unknown;
  /**
   * Artistic Style
   *
   * The artistic style of the image to be generated.
   */
  artistic_style?: string | unknown;
  /**
   * Style Medium
   *
   * The style medium of the image to be generated.
   */
  style_medium?: string | unknown;
  /**
   * Text Render
   *
   * A list of text to be rendered in the image.
   */
  text_render?: Array<unknown> | unknown;
  /**
   * Objects
   *
   * A list of objects in the image to be generated, along with their attributes and relationships to other objects in the image.
   */
  objects?: Array<PromptObject> | unknown;
  /**
   * Context
   *
   * The context of the image to be generated.
   */
  context?: string | unknown;
  /**
   * The photographic characteristics of the image to be generated.
   */
  photographic_characteristics?: PhotographicCharacteristics | unknown;
  /**
   * The aesthetics of the image to be generated.
   */
  aesthetics?: AestheticsType2 | unknown;
  /**
   * The lighting of the image to be generated.
   */
  lighting?: Lighting | unknown;
  /**
   * Short Description
   *
   * A short description of the image to be generated.
   */
  short_description?: string | unknown;
};

/**
 * Lighting
 */
export type Lighting = {
  /**
   * Shadows
   *
   * The shadows in the image to be generated.
   */
  shadows?: string | unknown;
  /**
   * Conditions
   *
   * The conditions of the lighting in the image to be generated.
   */
  conditions?: string | unknown;
  /**
   * Direction
   *
   * The direction of the lighting in the image to be generated.
   */
  direction?: string | unknown;
};

/**
 * Aesthetics
 */
export type AestheticsType2 = {
  /**
   * Preference Score
   *
   * The preference score of the image.
   */
  preference_score: string;
  /**
   * Composition
   *
   * The composition of the image to be generated.
   */
  composition?: string | unknown;
  /**
   * Mood Atmosphere
   *
   * The mood and atmosphere of the image to be generated.
   */
  mood_atmosphere?: string | unknown;
  /**
   * Aesthetic Score
   *
   * The aesthetic score of the image.
   */
  aesthetic_score: string;
  /**
   * Color Scheme
   *
   * The color scheme of the image to be generated.
   */
  color_scheme?: string | unknown;
};

/**
 * PhotographicCharacteristics
 */
export type PhotographicCharacteristics = {
  /**
   * Focus
   *
   * The focus in the image to be generated.
   */
  focus?: string | unknown;
  /**
   * Lens Focal Length
   *
   * The focal length of the lens in the image to be generated.
   */
  lens_focal_length?: string | unknown;
  /**
   * Camera Angle
   *
   * The angle of the camera in the image to be generated.
   */
  camera_angle?: string | unknown;
  /**
   * Depth Of Field
   *
   * The depth of field in the image to be generated.
   */
  depth_of_field?: string | unknown;
};

/**
 * PromptObject
 */
export type PromptObject = {
  /**
   * Relative Size
   *
   * The relative size of the object in the image.
   */
  relative_size?: string | unknown;
  /**
   * Description
   *
   * A description of the object to be generated.
   */
  description?: string | unknown;
  /**
   * Skin Tone And Texture
   *
   * The skin tone and texture of the object in the image.
   */
  skin_tone_and_texture?: string | unknown;
  /**
   * Appearance Details
   *
   * The appearance details of the object.
   */
  appearance_details?: string | unknown;
  /**
   * Number Of Objects
   *
   * The number of objects in the image.
   */
  number_of_objects?: number | unknown;
  /**
   * Pose
   *
   * The pose of the object in the image.
   */
  pose?: string | unknown;
  /**
   * Expression
   *
   * The expression of the object in the image.
   */
  expression?: string | unknown;
  /**
   * Shape And Color
   *
   * The shape and color of the object.
   */
  shape_and_color?: string | unknown;
  /**
   * Relationship
   *
   * The relationship of the object to other objects in the image.
   */
  relationship: string;
  /**
   * Texture
   *
   * The texture of the object.
   */
  texture?: string | unknown;
  /**
   * Gender
   *
   * The gender of the object in the image.
   */
  gender?: string | unknown;
  /**
   * Clothing
   *
   * The clothing of the object in the image.
   */
  clothing?: string | unknown;
  /**
   * Location
   *
   * The location of the object in the image.
   */
  location?: string | unknown;
  /**
   * Orientation
   *
   * The orientation of the object in the image.
   */
  orientation?: string | unknown;
  /**
   * Action
   *
   * The action of the object in the image.
   */
  action?: string | unknown;
};

export type FiboLiteGenerateStructuredPromptLiteOutput = unknown;

/**
 * StructuredPromptModel
 */
export type FiboLiteGenerateStructuredPromptLiteInput = {
  /**
   * Prompt
   *
   * Prompt for image generation.
   */
  prompt?: string | unknown;
  /**
   * Seed
   *
   * Random seed for reproducibility.
   */
  seed?: number;
  /**
   * The structured prompt to generate an image from.
   */
  structured_prompt?: BriaFiboVlmStructuredPrompt | unknown;
  /**
   * Image Url
   *
   * Reference image (file or URL).
   */
  image_url?: string | unknown;
};

export type FiboEditEditStructuredInstructionOutput = unknown;

/**
 * StructuredInstructionInputModel
 */
export type FiboEditEditStructuredInstructionInput = {
  /**
   * Sync Mode
   *
   * If true, returns the image directly in the response (increases latency).
   */
  sync_mode?: boolean;
  /**
   * Seed
   *
   * Random seed for reproducibility.
   */
  seed?: number;
  /**
   * Instruction
   *
   * Instruction for image editing.
   */
  instruction?: string | unknown;
  /**
   * Mask Url
   *
   * Reference image mask (file or URL). Optional.
   */
  mask_url?: string | unknown;
  /**
   * Image Url
   *
   * Reference image (file or URL).
   */
  image_url?: string | unknown;
};

/**
 * Aesthetics
 */
export type Aesthetics = {
  /**
   * Composition
   *
   * The composition of the image to be generated.
   */
  composition?: string | unknown;
  /**
   * Mood Atmosphere
   *
   * The mood and atmosphere of the image to be generated.
   */
  mood_atmosphere?: string | unknown;
  /**
   * Color Scheme
   *
   * The color scheme of the image to be generated.
   */
  color_scheme?: string | unknown;
};

export type FiboGenerateStructuredPromptOutput = unknown;

/**
 * StructuredPromptModel
 */
export type FiboGenerateStructuredPromptInput = {
  /**
   * Prompt
   *
   * Prompt for image generation.
   */
  prompt?: string | unknown;
  /**
   * Seed
   *
   * Random seed for reproducibility.
   */
  seed?: number;
  /**
   * The structured prompt to generate an image from.
   */
  structured_prompt?: StructuredPromptType2 | unknown;
  /**
   * Image Url
   *
   * Reference image (file or URL).
   */
  image_url?: string | unknown;
};

/**
 * StructuredPrompt
 */
export type StructuredPromptType2 = {
  /**
   * Background Setting
   *
   * The background setting of the image to be generated.
   */
  background_setting?: string | unknown;
  /**
   * Artistic Style
   *
   * The artistic style of the image to be generated.
   */
  artistic_style?: string | unknown;
  /**
   * The aesthetics of the image to be generated.
   */
  aesthetics?: Aesthetics | unknown;
  /**
   * Text Render
   *
   * A list of text to be rendered in the image.
   */
  text_render?: Array<unknown> | unknown;
  /**
   * Objects
   *
   * A list of objects in the image to be generated, along with their attributes and relationships to other objects in the image.
   */
  objects?: Array<PromptObject> | unknown;
  /**
   * Style Medium
   *
   * The style medium of the image to be generated.
   */
  style_medium?: string | unknown;
  /**
   * The photographic characteristics of the image to be generated.
   */
  photographic_characteristics?: PhotographicCharacteristics | unknown;
  /**
   * Context
   *
   * The context of the image to be generated.
   */
  context?: string | unknown;
  /**
   * The lighting of the image to be generated.
   */
  lighting?: Lighting | unknown;
  /**
   * Short Description
   *
   * A short description of the image to be generated.
   */
  short_description?: string | unknown;
};

/**
 * LightingDetails
 *
 * Lighting information for the image.
 */
export type LightingDetails = {
  /**
   * Shadows
   *
   * Describe the presence of shadows.
   */
  shadows?: string | unknown;
  /**
   * Conditions
   *
   * E.g., 'bright daylight', 'dim indoor', 'studio lighting', 'golden hour'.
   */
  conditions: string;
  /**
   * Direction
   *
   * E.g., 'front-lit', 'backlit', 'side-lit from left'.
   */
  direction: string;
};

/**
 * AestheticsDetails
 *
 * Aesthetic analysis of the image.
 */
export type AestheticsDetails = {
  /**
   * Preference Score
   *
   * E.g., 'very low', 'low', 'medium', 'high', 'very high'.
   */
  preference_score: string;
  /**
   * Composition
   *
   * E.g., 'rule of thirds', 'symmetrical', 'centered', 'leading lines'.
   */
  composition: string;
  /**
   * Mood Atmosphere
   *
   * E.g., 'serene', 'energetic', 'mysterious', 'joyful'.
   */
  mood_atmosphere: string;
  /**
   * Aesthetic Score
   *
   * E.g., 'very low', 'low', 'medium', 'high', 'very high'.
   */
  aesthetic_score: string;
  /**
   * Color Scheme
   *
   * E.g., 'monochromatic blue', 'warm complementary colors', 'high contrast'.
   */
  color_scheme: string;
};

/**
 * PhotographicCharacteristicsDetails
 *
 * Photographic characteristics of the image.
 */
export type PhotographicCharacteristicsDetails = {
  /**
   * Focus
   *
   * E.g., 'sharp focus on subject', 'soft focus', 'motion blur'.
   */
  focus: string;
  /**
   * Lens Focal Length
   *
   * E.g., 'wide-angle', 'telephoto', 'macro', 'fisheye'.
   */
  lens_focal_length: string;
  /**
   * Camera Angle
   *
   * E.g., 'eye-level', 'low angle', 'high angle', 'dutch angle'.
   */
  camera_angle: string;
  /**
   * Depth Of Field
   *
   * E.g., 'shallow', 'deep', 'bokeh background'.
   */
  depth_of_field: string;
};

/**
 * ObjectDescription
 *
 * Detailed object description with all attributes.
 */
export type ObjectDescription = {
  /**
   * Relative Size
   *
   * E.g., 'small', 'medium', 'large within frame'.
   */
  relative_size?: string | unknown;
  /**
   * Description
   *
   * Short description of the object.
   */
  description: string;
  /**
   * Skin Tone And Texture
   *
   * Describe the skin tone and texture.
   */
  skin_tone_and_texture?: string | unknown;
  /**
   * Appearance Details
   *
   * Any other notable visual details.
   */
  appearance_details?: string | unknown;
  /**
   * Number Of Objects
   *
   * The number of objects in the cluster.
   */
  number_of_objects?: number | unknown;
  /**
   * Expression
   *
   * Describe facial expression.
   */
  expression?: string | unknown;
  /**
   * Pose
   *
   * Describe the body position.
   */
  pose?: string | unknown;
  /**
   * Shape And Color
   *
   * Describe the basic shape and dominant color.
   */
  shape_and_color?: string | unknown;
  /**
   * Relationship
   *
   * Describe the relationship between the object and the other objects in the image.
   */
  relationship: string;
  /**
   * Texture
   *
   * E.g., 'smooth', 'rough', 'metallic', 'furry'.
   */
  texture?: string | unknown;
  /**
   * Gender
   *
   * Describe the gender of the human.
   */
  gender?: string | unknown;
  /**
   * Clothing
   *
   * Describe attire.
   */
  clothing?: string | unknown;
  /**
   * Location
   *
   * E.g., 'center', 'top-left', 'bottom-right foreground'.
   */
  location: string;
  /**
   * Orientation
   *
   * Describe the orientation of the human.
   */
  orientation?: string | unknown;
  /**
   * Action
   *
   * Describe the action of the human.
   */
  action?: string | unknown;
};

/**
 * TextRender
 *
 * Text rendering information in the image.
 */
export type TextRender = {
  /**
   * Text
   *
   * The text content.
   */
  text: string;
  /**
   * Font
   *
   * E.g., 'realistic', 'cartoonish', 'minimalist'.
   */
  font: string;
  /**
   * Color
   *
   * E.g., 'red', 'blue', 'green'.
   */
  color: string;
  /**
   * Location
   *
   * E.g., 'center', 'top-left', 'bottom-right foreground'.
   */
  location: string;
  /**
   * Appearance Details
   *
   * Any other notable visual details.
   */
  appearance_details?: string | unknown;
  /**
   * Size
   *
   * E.g., 'small', 'medium', 'large within frame'.
   */
  size: string;
};

/**
 * StructuredPrompt
 */
export type StructuredPrompt = {
  /**
   * Background Setting
   *
   * Describe the overall environment, setting, or background, including any notable background elements.
   */
  background_setting: string;
  /**
   * Artistic Style
   *
   * describe specific artistic characteristics, 3 words maximum.
   */
  artistic_style: string;
  /**
   * Style Medium
   *
   * Identify the artistic style or medium.
   */
  style_medium?: string | unknown;
  /**
   * Text Render
   *
   * List of text renders in the image.
   */
  text_render?: Array<TextRender> | unknown;
  /**
   * Subject Emotions
   *
   * Explicitly describe any visible emotions or expressions on subjects.
   */
  subject_emotions?: string | unknown;
  /**
   * Objects
   *
   * List of prominent foreground/midground objects.
   */
  objects: Array<ObjectDescription>;
  /**
   * Details about photographic characteristics.
   */
  photographic_characteristics?: PhotographicCharacteristicsDetails | unknown;
  aesthetics: AestheticsDetails;
  lighting: LightingDetails;
  /**
   * Context
   *
   * Provide any additional context that helps understand the image better.
   */
  context: string;
  /**
   * Short Description
   *
   * A concise summary of the image content, 200 words maximum.
   */
  short_description: string;
};

export type FiboLiteGenerateStructuredPromptOutput = unknown;

/**
 * StructuredPromptInput
 */
export type FiboLiteGenerateStructuredPromptInput = {
  /**
   * Prompt
   *
   * The prompt to generate.
   */
  prompt?: string | unknown;
  /**
   * Seed
   *
   * Seed for the random number generator.
   */
  seed?: number;
  /**
   * The structured prompt to generate.
   */
  structured_prompt?: StructuredPrompt | unknown;
  /**
   * Image Url
   *
   * Input image URL
   */
  image_url?: string | unknown;
};

/**
 * LottieOutput
 */
export type OmnilottieVideoToLottieOutput = {
  lottie_file: File;
};

/**
 * File
 */
export type File = {
  /**
   * File Size
   *
   * The size of the file in bytes.
   */
  file_size?: number | unknown;
  /**
   * File Name
   *
   * The name of the file. It will be auto-generated if not provided.
   */
  file_name?: string | unknown;
  /**
   * Content Type
   *
   * The mime type of the file.
   */
  content_type?: string | unknown;
  /**
   * Url
   *
   * The URL where the file can be downloaded from.
   */
  url: string;
};

/**
 * VideoToLottieInput
 */
export type OmnilottieVideoToLottieInput = {
  /**
   * Prompt
   *
   * Optional text description guiding the conversion.
   */
  prompt?: string | unknown;
  /**
   * Video Url
   *
   * URL of the video to convert into a Lottie animation.
   */
  video_url: string | Blob | File;
  /**
   * Top P
   *
   * Nucleus sampling probability threshold.
   */
  top_p?: number;
  /**
   * Max Tokens
   *
   * Maximum number of Lottie tokens to generate.
   */
  max_tokens?: number;
  /**
   * Temperature
   *
   * Sampling temperature for generation.
   */
  temperature?: number;
  /**
   * Top K
   *
   * Top-k sampling parameter.
   */
  top_k?: number;
};

/**
 * WaveformOutput
 */
export type FfmpegApiWaveformOutput = {
  /**
   * Waveform
   *
   * Normalized waveform data as an array of values between -1 and 1. The number of points is determined by audio duration × points_per_second.
   */
  waveform: Array<number>;
  /**
   * Duration
   *
   * Duration of the audio in seconds
   */
  duration: number;
  /**
   * Points
   *
   * Number of points in the waveform data
   */
  points: number;
  /**
   * Precision
   *
   * Number of decimal places used in the waveform values
   */
  precision: number;
};

/**
 * WaveformInput
 */
export type FfmpegApiWaveformInput = {
  /**
   * Points Per Second
   *
   * Controls how many points are sampled per second of audio. Lower values (e.g. 1-2) create a coarser waveform, higher values (e.g. 4-10) create a more detailed one.
   */
  points_per_second?: number;
  /**
   * Smoothing Window
   *
   * Size of the smoothing window. Higher values create a smoother waveform. Must be an odd number.
   */
  smoothing_window?: number;
  /**
   * Media Url
   *
   * URL of the audio file to analyze
   */
  media_url: string | Blob | File;
  /**
   * Precision
   *
   * Number of decimal places for the waveform values. Higher values provide more precision but increase payload size.
   */
  precision?: number;
};

/**
 * LoudnormSummary
 */
export type LoudnormSummary = {
  /**
   * Output Integrated
   *
   * Output integrated loudness in LUFS
   */
  output_integrated?: number | unknown;
  /**
   * Output Lra
   *
   * Output loudness range in LU
   */
  output_lra?: number | unknown;
  /**
   * Input Lra
   *
   * Input loudness range in LU
   */
  input_lra?: number | unknown;
  /**
   * Normalization Type
   *
   * Type of normalization applied (Dynamic/Linear)
   */
  normalization_type?: string | unknown;
  /**
   * Output True Peak
   *
   * Output true peak in dBTP
   */
  output_true_peak?: number | unknown;
  /**
   * Target Offset
   *
   * Target offset in LU
   */
  target_offset?: number | unknown;
  /**
   * Input Integrated
   *
   * Input integrated loudness in LUFS
   */
  input_integrated?: number | unknown;
  /**
   * Input True Peak
   *
   * Input true peak in dBTP
   */
  input_true_peak?: number | unknown;
  /**
   * Output Threshold
   *
   * Output threshold in LUFS
   */
  output_threshold?: number | unknown;
  /**
   * Input Threshold
   *
   * Input threshold in LUFS
   */
  input_threshold?: number | unknown;
};

/**
 * LoudnormOutput
 */
export type FfmpegApiLoudnormOutput = {
  /**
   * Structured loudness measurement summary (if requested)
   */
  summary?: LoudnormSummary | unknown;
  audio: File;
};

/**
 * LoudnormInput
 */
export type FfmpegApiLoudnormInput = {
  /**
   * Measured Lra
   *
   * Measured loudness range of input file in LU. Required for linear mode.
   */
  measured_lra?: number | unknown;
  /**
   * Print Summary
   *
   * Return loudness measurement summary with the normalized audio
   */
  print_summary?: boolean;
  /**
   * Offset
   *
   * Offset gain in dB applied before the true-peak limiter
   */
  offset?: number;
  /**
   * Measured I
   *
   * Measured integrated loudness of input file in LUFS. Required for linear mode.
   */
  measured_i?: number | unknown;
  /**
   * Measured Tp
   *
   * Measured true peak of input file in dBTP. Required for linear mode.
   */
  measured_tp?: number | unknown;
  /**
   * Linear
   *
   * Use linear normalization mode (single-pass). If false, uses dynamic mode (two-pass for better quality).
   */
  linear?: boolean;
  /**
   * Dual Mono
   *
   * Treat mono input files as dual-mono for correct EBU R128 measurement on stereo systems
   */
  dual_mono?: boolean;
  /**
   * Measured Thresh
   *
   * Measured threshold of input file in LUFS. Required for linear mode.
   */
  measured_thresh?: number | unknown;
  /**
   * True Peak
   *
   * Maximum true peak in dBTP.
   */
  true_peak?: number;
  /**
   * Audio Url
   *
   * URL of the audio file to normalize
   */
  audio_url: string | Blob | File;
  /**
   * Integrated Loudness
   *
   * Integrated loudness target in LUFS.
   */
  integrated_loudness?: number;
  /**
   * Loudness Range
   *
   * Loudness range target in LU
   */
  loudness_range?: number;
};

/**
 * LottieOutput
 */
export type OmnilottieOutput = {
  lottie_file: File;
};

/**
 * TextToLottieInput
 */
export type OmnilottieInput = {
  /**
   * Prompt
   *
   * Text description of the Lottie animation to generate.
   */
  prompt: string;
  /**
   * Top P
   *
   * Nucleus sampling probability threshold.
   */
  top_p?: number;
  /**
   * Max Tokens
   *
   * Maximum number of Lottie tokens to generate.
   */
  max_tokens?: number;
  /**
   * Temperature
   *
   * Sampling temperature for generation.
   */
  temperature?: number;
  /**
   * Top K
   *
   * Top-k sampling parameter.
   */
  top_k?: number;
};

/**
 * LottieOutput
 */
export type OmnilottieImageToLottieOutput = {
  lottie_file: File;
};

/**
 * ImageToLottieInput
 */
export type OmnilottieImageToLottieInput = {
  /**
   * Prompt
   *
   * Text description guiding the animation of the image.
   */
  prompt: string;
  /**
   * Image Url
   *
   * URL of the reference image to animate.
   */
  image_url: string | Blob | File;
  /**
   * Top P
   *
   * Nucleus sampling probability threshold.
   */
  top_p?: number;
  /**
   * Max Tokens
   *
   * Maximum number of Lottie tokens to generate.
   */
  max_tokens?: number;
  /**
   * Temperature
   *
   * Sampling temperature for generation.
   */
  temperature?: number;
  /**
   * Top K
   *
   * Top-k sampling parameter.
   */
  top_k?: number;
};

/**
 * AudioTrack
 */
export type AudioTrack = {
  /**
   * Codec
   *
   * Audio codec used (e.g., 'aac', 'mp3')
   */
  codec: string;
  /**
   * Bitrate
   *
   * Audio bitrate in bits per second
   */
  bitrate: number;
  /**
   * Sample Rate
   *
   * Audio sample rate in Hz
   */
  sample_rate: number;
  /**
   * Channels
   *
   * Number of audio channels
   */
  channels: number;
};

/**
 * Resolution
 */
export type Resolution = {
  /**
   * Height
   *
   * Height of the video in pixels
   */
  height: number;
  /**
   * Aspect Ratio
   *
   * Display aspect ratio (e.g., '16:9')
   */
  aspect_ratio: string;
  /**
   * Width
   *
   * Width of the video in pixels
   */
  width: number;
};

/**
 * VideoFormat
 */
export type VideoFormat = {
  /**
   * Profile
   *
   * Codec profile (e.g., 'main', 'high')
   */
  profile: string;
  /**
   * Level
   *
   * Codec level (e.g., 4.1)
   */
  level: number;
  /**
   * Pixel Format
   *
   * Pixel format used (e.g., 'yuv420p')
   */
  pixel_format: string;
  /**
   * Video Codec
   *
   * Video codec used (e.g., 'h264')
   */
  video_codec: string;
  /**
   * Container
   *
   * Container format of the video
   */
  container: string;
  /**
   * Bitrate
   *
   * Video bitrate in bits per second
   */
  bitrate: number;
};

/**
 * Audio
 */
export type Audio = {
  /**
   * File Size
   *
   * Size of the file in bytes
   */
  file_size: number;
  /**
   * Duration
   *
   * Duration of the media in seconds
   */
  duration: number;
  /**
   * Channels
   *
   * Number of audio channels
   */
  channels: number;
  /**
   * Url
   *
   * URL where the media file can be accessed
   */
  url: string;
  /**
   * Media Type
   *
   * Type of media (always 'audio')
   */
  media_type?: string;
  /**
   * Codec
   *
   * Codec used to encode the media
   */
  codec: string;
  /**
   * File Name
   *
   * Original filename of the media
   */
  file_name: string;
  /**
   * Sample Rate
   *
   * Audio sample rate in Hz
   */
  sample_rate: number;
  /**
   * Content Type
   *
   * MIME type of the media file
   */
  content_type: string;
  /**
   * Container
   *
   * Container format of the media file (e.g., 'mp4', 'mov')
   */
  container: string;
  /**
   * Bitrate
   *
   * Overall bitrate of the media in bits per second
   */
  bitrate: number;
};

/**
 * Video
 */
export type Video = {
  /**
   * File Size
   *
   * Size of the file in bytes
   */
  file_size: number;
  /**
   * Timebase
   *
   * Time base used for frame timestamps
   */
  timebase: string;
  /**
   * Start Frame Url
   *
   * URL of the extracted first frame
   */
  start_frame_url?: string | unknown;
  /**
   * Duration
   *
   * Duration of the media in seconds
   */
  duration: number;
  /**
   * Url
   *
   * URL where the media file can be accessed
   */
  url: string;
  /**
   * Media Type
   *
   * Type of media (always 'video')
   */
  media_type?: string;
  /**
   * Codec
   *
   * Codec used to encode the media
   */
  codec: string;
  /**
   * Fps
   *
   * Frames per second
   */
  fps: number;
  /**
   * End Frame Url
   *
   * URL of the extracted last frame
   */
  end_frame_url?: string | unknown;
  /**
   * Content Type
   *
   * MIME type of the media file
   */
  content_type: string;
  /**
   * Container
   *
   * Container format of the media file (e.g., 'mp4', 'mov')
   */
  container: string;
  /**
   * Bitrate
   *
   * Overall bitrate of the media in bits per second
   */
  bitrate: number;
  format: VideoFormat;
  resolution: Resolution;
  /**
   * Frame Count
   *
   * Total number of frames in the video
   */
  frame_count: number;
  /**
   * File Name
   *
   * Original filename of the media
   */
  file_name: string;
  /**
   * Audio track information if video has audio
   */
  audio?: AudioTrack | unknown;
};

/**
 * MetadataOutput
 */
export type FfmpegApiMetadataOutput = {
  /**
   * Media
   *
   * Metadata for the analyzed media file (either Video or Audio)
   */
  media: Video | Audio;
};

/**
 * MetadataInput
 */
export type FfmpegApiMetadataInput = {
  /**
   * Extract Frames
   *
   * Whether to extract the start and end frames for videos. Note that when true the request will be slower.
   */
  extract_frames?: boolean;
  /**
   * Media Url
   *
   * URL of the media file (video or audio) to analyze
   */
  media_url: string | Blob | File;
};

/**
 * TextOutput
 */
export type BagelUnderstandOutput = {
  /**
   * Prompt
   *
   * The query used for the generation.
   */
  prompt: string;
  /**
   * Text
   *
   * The answer to the query.
   */
  text: string;
  /**
   * Timings
   *
   * The timings of the generation.
   */
  timings: {
    [key: string]: unknown;
  };
  /**
   * Seed
   *
   * The seed used for the generation.
   */
  seed: number;
};

/**
 * ImageUnderstandingInput
 */
export type BagelUnderstandInput = {
  /**
   * Prompt
   *
   * The prompt to query the image with.
   */
  prompt: string;
  /**
   * Seed
   *
   * The seed to use for the generation.
   */
  seed?: number;
  /**
   * Image Url
   *
   * The image for the query.
   */
  image_url: string | Blob | File;
};

export type QueueStatus = {
  status: "IN_QUEUE" | "IN_PROGRESS" | "COMPLETED";
  /**
   * The request id.
   */
  request_id: string;
  /**
   * The response url.
   */
  response_url?: string;
  /**
   * The status url.
   */
  status_url?: string;
  /**
   * The cancel url.
   */
  cancel_url?: string;
  /**
   * The logs.
   */
  logs?: {
    [key: string]: unknown;
  };
  /**
   * The metrics.
   */
  metrics?: {
    [key: string]: unknown;
  };
  /**
   * The queue position.
   */
  queue_position?: number;
};

export type GetFalAiBagelUnderstandRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/bagel/understand/requests/{request_id}/status";
};

export type GetFalAiBagelUnderstandRequestsByRequestIdStatusResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type GetFalAiBagelUnderstandRequestsByRequestIdStatusResponse =
  GetFalAiBagelUnderstandRequestsByRequestIdStatusResponses[keyof GetFalAiBagelUnderstandRequestsByRequestIdStatusResponses];

export type PutFalAiBagelUnderstandRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/bagel/understand/requests/{request_id}/cancel";
};

export type PutFalAiBagelUnderstandRequestsByRequestIdCancelResponses = {
  /**
   * The request was cancelled.
   */
  200: {
    /**
     * Whether the request was cancelled successfully.
     */
    success?: boolean;
  };
};

export type PutFalAiBagelUnderstandRequestsByRequestIdCancelResponse =
  PutFalAiBagelUnderstandRequestsByRequestIdCancelResponses[keyof PutFalAiBagelUnderstandRequestsByRequestIdCancelResponses];

export type PostFalAiBagelUnderstandData = {
  body: BagelUnderstandInput;
  path?: never;
  query?: never;
  url: "/fal-ai/bagel/understand";
};

export type PostFalAiBagelUnderstandResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiBagelUnderstandResponse =
  PostFalAiBagelUnderstandResponses[keyof PostFalAiBagelUnderstandResponses];

export type GetFalAiBagelUnderstandRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/bagel/understand/requests/{request_id}";
};

export type GetFalAiBagelUnderstandRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: BagelUnderstandOutput;
};

export type GetFalAiBagelUnderstandRequestsByRequestIdResponse =
  GetFalAiBagelUnderstandRequestsByRequestIdResponses[keyof GetFalAiBagelUnderstandRequestsByRequestIdResponses];

export type GetFalAiFfmpegApiMetadataRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/ffmpeg-api/metadata/requests/{request_id}/status";
};

export type GetFalAiFfmpegApiMetadataRequestsByRequestIdStatusResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type GetFalAiFfmpegApiMetadataRequestsByRequestIdStatusResponse =
  GetFalAiFfmpegApiMetadataRequestsByRequestIdStatusResponses[keyof GetFalAiFfmpegApiMetadataRequestsByRequestIdStatusResponses];

export type PutFalAiFfmpegApiMetadataRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/ffmpeg-api/metadata/requests/{request_id}/cancel";
};

export type PutFalAiFfmpegApiMetadataRequestsByRequestIdCancelResponses = {
  /**
   * The request was cancelled.
   */
  200: {
    /**
     * Whether the request was cancelled successfully.
     */
    success?: boolean;
  };
};

export type PutFalAiFfmpegApiMetadataRequestsByRequestIdCancelResponse =
  PutFalAiFfmpegApiMetadataRequestsByRequestIdCancelResponses[keyof PutFalAiFfmpegApiMetadataRequestsByRequestIdCancelResponses];

export type PostFalAiFfmpegApiMetadataData = {
  body: FfmpegApiMetadataInput;
  path?: never;
  query?: never;
  url: "/fal-ai/ffmpeg-api/metadata";
};

export type PostFalAiFfmpegApiMetadataResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiFfmpegApiMetadataResponse =
  PostFalAiFfmpegApiMetadataResponses[keyof PostFalAiFfmpegApiMetadataResponses];

export type GetFalAiFfmpegApiMetadataRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/ffmpeg-api/metadata/requests/{request_id}";
};

export type GetFalAiFfmpegApiMetadataRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: FfmpegApiMetadataOutput;
};

export type GetFalAiFfmpegApiMetadataRequestsByRequestIdResponse =
  GetFalAiFfmpegApiMetadataRequestsByRequestIdResponses[keyof GetFalAiFfmpegApiMetadataRequestsByRequestIdResponses];

export type GetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/omnilottie/image-to-lottie/requests/{request_id}/status";
};

export type GetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusResponse =
  GetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusResponses[keyof GetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusResponses];

export type PutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/omnilottie/image-to-lottie/requests/{request_id}/cancel";
};

export type PutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelResponse =
  PutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelResponses[keyof PutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelResponses];

export type PostFalAiOmnilottieImageToLottieData = {
  body: OmnilottieImageToLottieInput;
  path?: never;
  query?: never;
  url: "/fal-ai/omnilottie/image-to-lottie";
};

export type PostFalAiOmnilottieImageToLottieResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiOmnilottieImageToLottieResponse =
  PostFalAiOmnilottieImageToLottieResponses[keyof PostFalAiOmnilottieImageToLottieResponses];

export type GetFalAiOmnilottieImageToLottieRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/omnilottie/image-to-lottie/requests/{request_id}";
};

export type GetFalAiOmnilottieImageToLottieRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: OmnilottieImageToLottieOutput;
};

export type GetFalAiOmnilottieImageToLottieRequestsByRequestIdResponse =
  GetFalAiOmnilottieImageToLottieRequestsByRequestIdResponses[keyof GetFalAiOmnilottieImageToLottieRequestsByRequestIdResponses];

export type GetFalAiOmnilottieRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/omnilottie/requests/{request_id}/status";
};

export type GetFalAiOmnilottieRequestsByRequestIdStatusResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type GetFalAiOmnilottieRequestsByRequestIdStatusResponse =
  GetFalAiOmnilottieRequestsByRequestIdStatusResponses[keyof GetFalAiOmnilottieRequestsByRequestIdStatusResponses];

export type PutFalAiOmnilottieRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/omnilottie/requests/{request_id}/cancel";
};

export type PutFalAiOmnilottieRequestsByRequestIdCancelResponses = {
  /**
   * The request was cancelled.
   */
  200: {
    /**
     * Whether the request was cancelled successfully.
     */
    success?: boolean;
  };
};

export type PutFalAiOmnilottieRequestsByRequestIdCancelResponse =
  PutFalAiOmnilottieRequestsByRequestIdCancelResponses[keyof PutFalAiOmnilottieRequestsByRequestIdCancelResponses];

export type PostFalAiOmnilottieData = {
  body: OmnilottieInput;
  path?: never;
  query?: never;
  url: "/fal-ai/omnilottie";
};

export type PostFalAiOmnilottieResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiOmnilottieResponse =
  PostFalAiOmnilottieResponses[keyof PostFalAiOmnilottieResponses];

export type GetFalAiOmnilottieRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/omnilottie/requests/{request_id}";
};

export type GetFalAiOmnilottieRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: OmnilottieOutput;
};

export type GetFalAiOmnilottieRequestsByRequestIdResponse =
  GetFalAiOmnilottieRequestsByRequestIdResponses[keyof GetFalAiOmnilottieRequestsByRequestIdResponses];

export type GetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/ffmpeg-api/loudnorm/requests/{request_id}/status";
};

export type GetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type GetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusResponse =
  GetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusResponses[keyof GetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusResponses];

export type PutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/ffmpeg-api/loudnorm/requests/{request_id}/cancel";
};

export type PutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelResponses = {
  /**
   * The request was cancelled.
   */
  200: {
    /**
     * Whether the request was cancelled successfully.
     */
    success?: boolean;
  };
};

export type PutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelResponse =
  PutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelResponses[keyof PutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelResponses];

export type PostFalAiFfmpegApiLoudnormData = {
  body: FfmpegApiLoudnormInput;
  path?: never;
  query?: never;
  url: "/fal-ai/ffmpeg-api/loudnorm";
};

export type PostFalAiFfmpegApiLoudnormResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiFfmpegApiLoudnormResponse =
  PostFalAiFfmpegApiLoudnormResponses[keyof PostFalAiFfmpegApiLoudnormResponses];

export type GetFalAiFfmpegApiLoudnormRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/ffmpeg-api/loudnorm/requests/{request_id}";
};

export type GetFalAiFfmpegApiLoudnormRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: FfmpegApiLoudnormOutput;
};

export type GetFalAiFfmpegApiLoudnormRequestsByRequestIdResponse =
  GetFalAiFfmpegApiLoudnormRequestsByRequestIdResponses[keyof GetFalAiFfmpegApiLoudnormRequestsByRequestIdResponses];

export type GetFalAiFfmpegApiWaveformRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/ffmpeg-api/waveform/requests/{request_id}/status";
};

export type GetFalAiFfmpegApiWaveformRequestsByRequestIdStatusResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type GetFalAiFfmpegApiWaveformRequestsByRequestIdStatusResponse =
  GetFalAiFfmpegApiWaveformRequestsByRequestIdStatusResponses[keyof GetFalAiFfmpegApiWaveformRequestsByRequestIdStatusResponses];

export type PutFalAiFfmpegApiWaveformRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/ffmpeg-api/waveform/requests/{request_id}/cancel";
};

export type PutFalAiFfmpegApiWaveformRequestsByRequestIdCancelResponses = {
  /**
   * The request was cancelled.
   */
  200: {
    /**
     * Whether the request was cancelled successfully.
     */
    success?: boolean;
  };
};

export type PutFalAiFfmpegApiWaveformRequestsByRequestIdCancelResponse =
  PutFalAiFfmpegApiWaveformRequestsByRequestIdCancelResponses[keyof PutFalAiFfmpegApiWaveformRequestsByRequestIdCancelResponses];

export type PostFalAiFfmpegApiWaveformData = {
  body: FfmpegApiWaveformInput;
  path?: never;
  query?: never;
  url: "/fal-ai/ffmpeg-api/waveform";
};

export type PostFalAiFfmpegApiWaveformResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiFfmpegApiWaveformResponse =
  PostFalAiFfmpegApiWaveformResponses[keyof PostFalAiFfmpegApiWaveformResponses];

export type GetFalAiFfmpegApiWaveformRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/ffmpeg-api/waveform/requests/{request_id}";
};

export type GetFalAiFfmpegApiWaveformRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: FfmpegApiWaveformOutput;
};

export type GetFalAiFfmpegApiWaveformRequestsByRequestIdResponse =
  GetFalAiFfmpegApiWaveformRequestsByRequestIdResponses[keyof GetFalAiFfmpegApiWaveformRequestsByRequestIdResponses];

export type GetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/fal-ai/omnilottie/video-to-lottie/requests/{request_id}/status";
};

export type GetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusResponse =
  GetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusResponses[keyof GetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusResponses];

export type PutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/omnilottie/video-to-lottie/requests/{request_id}/cancel";
};

export type PutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelResponse =
  PutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelResponses[keyof PutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelResponses];

export type PostFalAiOmnilottieVideoToLottieData = {
  body: OmnilottieVideoToLottieInput;
  path?: never;
  query?: never;
  url: "/fal-ai/omnilottie/video-to-lottie";
};

export type PostFalAiOmnilottieVideoToLottieResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiOmnilottieVideoToLottieResponse =
  PostFalAiOmnilottieVideoToLottieResponses[keyof PostFalAiOmnilottieVideoToLottieResponses];

export type GetFalAiOmnilottieVideoToLottieRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/omnilottie/video-to-lottie/requests/{request_id}";
};

export type GetFalAiOmnilottieVideoToLottieRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: OmnilottieVideoToLottieOutput;
};

export type GetFalAiOmnilottieVideoToLottieRequestsByRequestIdResponse =
  GetFalAiOmnilottieVideoToLottieRequestsByRequestIdResponses[keyof GetFalAiOmnilottieVideoToLottieRequestsByRequestIdResponses];

export type GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: {
      /**
       * Whether to include logs (`1`) in the response or not (`0`).
       */
      logs?: number;
    };
    url: "/bria/fibo-lite/generate/structured_prompt/requests/{request_id}/status";
  };

export type GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusResponse =
  GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusResponses[keyof GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusResponses];

export type PutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: never;
    url: "/bria/fibo-lite/generate/structured_prompt/requests/{request_id}/cancel";
  };

export type PutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelResponse =
  PutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelResponses[keyof PutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelResponses];

export type PostBriaFiboLiteGenerateStructuredPromptData = {
  body: FiboLiteGenerateStructuredPromptInput;
  path?: never;
  query?: never;
  url: "/bria/fibo-lite/generate/structured_prompt";
};

export type PostBriaFiboLiteGenerateStructuredPromptResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostBriaFiboLiteGenerateStructuredPromptResponse =
  PostBriaFiboLiteGenerateStructuredPromptResponses[keyof PostBriaFiboLiteGenerateStructuredPromptResponses];

export type GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/bria/fibo-lite/generate/structured_prompt/requests/{request_id}";
};

export type GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdResponses =
  {
    /**
     * Result of the request.
     */
    200: FiboLiteGenerateStructuredPromptOutput;
  };

export type GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdResponse =
  GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdResponses[keyof GetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdResponses];

export type GetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/bria/fibo/generate/structured_prompt/requests/{request_id}/status";
};

export type GetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusResponse =
  GetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusResponses[keyof GetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusResponses];

export type PutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/bria/fibo/generate/structured_prompt/requests/{request_id}/cancel";
};

export type PutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelResponse =
  PutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelResponses[keyof PutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelResponses];

export type PostBriaFiboGenerateStructuredPromptData = {
  body: FiboGenerateStructuredPromptInput;
  path?: never;
  query?: never;
  url: "/bria/fibo/generate/structured_prompt";
};

export type PostBriaFiboGenerateStructuredPromptResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostBriaFiboGenerateStructuredPromptResponse =
  PostBriaFiboGenerateStructuredPromptResponses[keyof PostBriaFiboGenerateStructuredPromptResponses];

export type GetBriaFiboGenerateStructuredPromptRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/bria/fibo/generate/structured_prompt/requests/{request_id}";
};

export type GetBriaFiboGenerateStructuredPromptRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: FiboGenerateStructuredPromptOutput;
};

export type GetBriaFiboGenerateStructuredPromptRequestsByRequestIdResponse =
  GetBriaFiboGenerateStructuredPromptRequestsByRequestIdResponses[keyof GetBriaFiboGenerateStructuredPromptRequestsByRequestIdResponses];

export type GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: {
      /**
       * Whether to include logs (`1`) in the response or not (`0`).
       */
      logs?: number;
    };
    url: "/bria/fibo-edit/edit/structured_instruction/requests/{request_id}/status";
  };

export type GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusResponse =
  GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusResponses[keyof GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusResponses];

export type PutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: never;
    url: "/bria/fibo-edit/edit/structured_instruction/requests/{request_id}/cancel";
  };

export type PutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelResponse =
  PutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelResponses[keyof PutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelResponses];

export type PostBriaFiboEditEditStructuredInstructionData = {
  body: FiboEditEditStructuredInstructionInput;
  path?: never;
  query?: never;
  url: "/bria/fibo-edit/edit/structured_instruction";
};

export type PostBriaFiboEditEditStructuredInstructionResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostBriaFiboEditEditStructuredInstructionResponse =
  PostBriaFiboEditEditStructuredInstructionResponses[keyof PostBriaFiboEditEditStructuredInstructionResponses];

export type GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/bria/fibo-edit/edit/structured_instruction/requests/{request_id}";
};

export type GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdResponses =
  {
    /**
     * Result of the request.
     */
    200: FiboEditEditStructuredInstructionOutput;
  };

export type GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdResponse =
  GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdResponses[keyof GetBriaFiboEditEditStructuredInstructionRequestsByRequestIdResponses];

export type GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: {
      /**
       * Whether to include logs (`1`) in the response or not (`0`).
       */
      logs?: number;
    };
    url: "/bria/fibo-lite/generate/structured_prompt/lite/requests/{request_id}/status";
  };

export type GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusResponse =
  GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusResponses[keyof GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusResponses];

export type PutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: never;
    url: "/bria/fibo-lite/generate/structured_prompt/lite/requests/{request_id}/cancel";
  };

export type PutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelResponse =
  PutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelResponses[keyof PutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelResponses];

export type PostBriaFiboLiteGenerateStructuredPromptLiteData = {
  body: FiboLiteGenerateStructuredPromptLiteInput;
  path?: never;
  query?: never;
  url: "/bria/fibo-lite/generate/structured_prompt/lite";
};

export type PostBriaFiboLiteGenerateStructuredPromptLiteResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostBriaFiboLiteGenerateStructuredPromptLiteResponse =
  PostBriaFiboLiteGenerateStructuredPromptLiteResponses[keyof PostBriaFiboLiteGenerateStructuredPromptLiteResponses];

export type GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: never;
    url: "/bria/fibo-lite/generate/structured_prompt/lite/requests/{request_id}";
  };

export type GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdResponses =
  {
    /**
     * Result of the request.
     */
    200: FiboLiteGenerateStructuredPromptLiteOutput;
  };

export type GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdResponse =
  GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdResponses[keyof GetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdResponses];
