// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * Lighting
 */
export const zLighting = z.object({
  shadows: z.union([z.string(), z.unknown()]).optional(),
  conditions: z.union([z.string(), z.unknown()]).optional(),
  direction: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * Aesthetics
 */
export const zAestheticsType2 = z.object({
  preference_score: z.string().register(z.globalRegistry, {
    description: "The preference score of the image.",
  }),
  composition: z.union([z.string(), z.unknown()]).optional(),
  mood_atmosphere: z.union([z.string(), z.unknown()]).optional(),
  aesthetic_score: z.string().register(z.globalRegistry, {
    description: "The aesthetic score of the image.",
  }),
  color_scheme: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * PhotographicCharacteristics
 */
export const zPhotographicCharacteristics = z.object({
  focus: z.union([z.string(), z.unknown()]).optional(),
  lens_focal_length: z.union([z.string(), z.unknown()]).optional(),
  camera_angle: z.union([z.string(), z.unknown()]).optional(),
  depth_of_field: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * PromptObject
 */
export const zPromptObject = z.object({
  relative_size: z.union([z.string(), z.unknown()]).optional(),
  description: z.union([z.string(), z.unknown()]).optional(),
  skin_tone_and_texture: z.union([z.string(), z.unknown()]).optional(),
  appearance_details: z.union([z.string(), z.unknown()]).optional(),
  number_of_objects: z.union([z.int(), z.unknown()]).optional(),
  pose: z.union([z.string(), z.unknown()]).optional(),
  expression: z.union([z.string(), z.unknown()]).optional(),
  shape_and_color: z.union([z.string(), z.unknown()]).optional(),
  relationship: z.string().register(z.globalRegistry, {
    description:
      "The relationship of the object to other objects in the image.",
  }),
  texture: z.union([z.string(), z.unknown()]).optional(),
  gender: z.union([z.string(), z.unknown()]).optional(),
  clothing: z.union([z.string(), z.unknown()]).optional(),
  location: z.union([z.string(), z.unknown()]).optional(),
  orientation: z.union([z.string(), z.unknown()]).optional(),
  action: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * StructuredPrompt
 */
export const zBriaFiboVlmStructuredPrompt = z.object({
  background_setting: z.union([z.string(), z.unknown()]).optional(),
  artistic_style: z.union([z.string(), z.unknown()]).optional(),
  style_medium: z.union([z.string(), z.unknown()]).optional(),
  text_render: z.union([z.array(z.unknown()), z.unknown()]).optional(),
  objects: z.union([z.array(zPromptObject), z.unknown()]).optional(),
  context: z.union([z.string(), z.unknown()]).optional(),
  photographic_characteristics: z
    .union([zPhotographicCharacteristics, z.unknown()])
    .optional(),
  aesthetics: z.union([zAestheticsType2, z.unknown()]).optional(),
  lighting: z.union([zLighting, z.unknown()]).optional(),
  short_description: z.union([z.string(), z.unknown()]).optional(),
});

export const zFiboLiteGenerateStructuredPromptLiteOutput = z.unknown();

/**
 * StructuredPromptModel
 */
export const zFiboLiteGenerateStructuredPromptLiteInput = z.object({
  prompt: z.union([z.string(), z.unknown()]).optional(),
  seed: z
    .int()
    .register(z.globalRegistry, {
      description: "Random seed for reproducibility.",
    })
    .optional()
    .default(5555),
  structured_prompt: z
    .union([zBriaFiboVlmStructuredPrompt, z.unknown()])
    .optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
});

export const zFiboEditEditStructuredInstructionOutput = z.unknown();

/**
 * StructuredInstructionInputModel
 */
export const zFiboEditEditStructuredInstructionInput = z.object({
  sync_mode: z
    .boolean()
    .register(z.globalRegistry, {
      description:
        "If true, returns the image directly in the response (increases latency).",
    })
    .optional()
    .default(false),
  seed: z
    .int()
    .register(z.globalRegistry, {
      description: "Random seed for reproducibility.",
    })
    .optional()
    .default(5555),
  instruction: z.union([z.string(), z.unknown()]).optional(),
  mask_url: z.union([z.string(), z.unknown()]).optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * Aesthetics
 */
export const zAesthetics = z.object({
  composition: z.union([z.string(), z.unknown()]).optional(),
  mood_atmosphere: z.union([z.string(), z.unknown()]).optional(),
  color_scheme: z.union([z.string(), z.unknown()]).optional(),
});

export const zFiboGenerateStructuredPromptOutput = z.unknown();

/**
 * StructuredPrompt
 */
export const zStructuredPromptType2 = z.object({
  background_setting: z.union([z.string(), z.unknown()]).optional(),
  artistic_style: z.union([z.string(), z.unknown()]).optional(),
  aesthetics: z.union([zAesthetics, z.unknown()]).optional(),
  text_render: z.union([z.array(z.unknown()), z.unknown()]).optional(),
  objects: z.union([z.array(zPromptObject), z.unknown()]).optional(),
  style_medium: z.union([z.string(), z.unknown()]).optional(),
  photographic_characteristics: z
    .union([zPhotographicCharacteristics, z.unknown()])
    .optional(),
  context: z.union([z.string(), z.unknown()]).optional(),
  lighting: z.union([zLighting, z.unknown()]).optional(),
  short_description: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * StructuredPromptModel
 */
export const zFiboGenerateStructuredPromptInput = z.object({
  prompt: z.union([z.string(), z.unknown()]).optional(),
  seed: z
    .int()
    .register(z.globalRegistry, {
      description: "Random seed for reproducibility.",
    })
    .optional()
    .default(5555),
  structured_prompt: z.union([zStructuredPromptType2, z.unknown()]).optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * LightingDetails
 *
 * Lighting information for the image.
 */
export const zLightingDetails = z
  .object({
    shadows: z.union([z.string(), z.unknown()]).optional(),
    conditions: z.string().register(z.globalRegistry, {
      description:
        "E.g., 'bright daylight', 'dim indoor', 'studio lighting', 'golden hour'.",
    }),
    direction: z.string().register(z.globalRegistry, {
      description: "E.g., 'front-lit', 'backlit', 'side-lit from left'.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Lighting information for the image.",
  });

/**
 * AestheticsDetails
 *
 * Aesthetic analysis of the image.
 */
export const zAestheticsDetails = z
  .object({
    preference_score: z.string().register(z.globalRegistry, {
      description: "E.g., 'very low', 'low', 'medium', 'high', 'very high'.",
    }),
    composition: z.string().register(z.globalRegistry, {
      description:
        "E.g., 'rule of thirds', 'symmetrical', 'centered', 'leading lines'.",
    }),
    mood_atmosphere: z.string().register(z.globalRegistry, {
      description: "E.g., 'serene', 'energetic', 'mysterious', 'joyful'.",
    }),
    aesthetic_score: z.string().register(z.globalRegistry, {
      description: "E.g., 'very low', 'low', 'medium', 'high', 'very high'.",
    }),
    color_scheme: z.string().register(z.globalRegistry, {
      description:
        "E.g., 'monochromatic blue', 'warm complementary colors', 'high contrast'.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Aesthetic analysis of the image.",
  });

/**
 * PhotographicCharacteristicsDetails
 *
 * Photographic characteristics of the image.
 */
export const zPhotographicCharacteristicsDetails = z
  .object({
    focus: z.string().register(z.globalRegistry, {
      description:
        "E.g., 'sharp focus on subject', 'soft focus', 'motion blur'.",
    }),
    lens_focal_length: z.string().register(z.globalRegistry, {
      description: "E.g., 'wide-angle', 'telephoto', 'macro', 'fisheye'.",
    }),
    camera_angle: z.string().register(z.globalRegistry, {
      description:
        "E.g., 'eye-level', 'low angle', 'high angle', 'dutch angle'.",
    }),
    depth_of_field: z.string().register(z.globalRegistry, {
      description: "E.g., 'shallow', 'deep', 'bokeh background'.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Photographic characteristics of the image.",
  });

/**
 * ObjectDescription
 *
 * Detailed object description with all attributes.
 */
export const zObjectDescription = z
  .object({
    relative_size: z.union([z.string(), z.unknown()]).optional(),
    description: z.string().register(z.globalRegistry, {
      description: "Short description of the object.",
    }),
    skin_tone_and_texture: z.union([z.string(), z.unknown()]).optional(),
    appearance_details: z.union([z.string(), z.unknown()]).optional(),
    number_of_objects: z.union([z.int(), z.unknown()]).optional(),
    expression: z.union([z.string(), z.unknown()]).optional(),
    pose: z.union([z.string(), z.unknown()]).optional(),
    shape_and_color: z.union([z.string(), z.unknown()]).optional(),
    relationship: z.string().register(z.globalRegistry, {
      description:
        "Describe the relationship between the object and the other objects in the image.",
    }),
    texture: z.union([z.string(), z.unknown()]).optional(),
    gender: z.union([z.string(), z.unknown()]).optional(),
    clothing: z.union([z.string(), z.unknown()]).optional(),
    location: z.string().register(z.globalRegistry, {
      description: "E.g., 'center', 'top-left', 'bottom-right foreground'.",
    }),
    orientation: z.union([z.string(), z.unknown()]).optional(),
    action: z.union([z.string(), z.unknown()]).optional(),
  })
  .register(z.globalRegistry, {
    description: "Detailed object description with all attributes.",
  });

/**
 * TextRender
 *
 * Text rendering information in the image.
 */
export const zTextRender = z
  .object({
    text: z.string().register(z.globalRegistry, {
      description: "The text content.",
    }),
    font: z.string().register(z.globalRegistry, {
      description: "E.g., 'realistic', 'cartoonish', 'minimalist'.",
    }),
    color: z.string().register(z.globalRegistry, {
      description: "E.g., 'red', 'blue', 'green'.",
    }),
    location: z.string().register(z.globalRegistry, {
      description: "E.g., 'center', 'top-left', 'bottom-right foreground'.",
    }),
    appearance_details: z.union([z.string(), z.unknown()]).optional(),
    size: z.string().register(z.globalRegistry, {
      description: "E.g., 'small', 'medium', 'large within frame'.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Text rendering information in the image.",
  });

/**
 * StructuredPrompt
 */
export const zStructuredPrompt = z.object({
  background_setting: z.string().register(z.globalRegistry, {
    description:
      "Describe the overall environment, setting, or background, including any notable background elements.",
  }),
  artistic_style: z.string().register(z.globalRegistry, {
    description: "describe specific artistic characteristics, 3 words maximum.",
  }),
  style_medium: z.union([z.string(), z.unknown()]).optional(),
  text_render: z.union([z.array(zTextRender), z.unknown()]).optional(),
  subject_emotions: z.union([z.string(), z.unknown()]).optional(),
  objects: z.array(zObjectDescription).register(z.globalRegistry, {
    description: "List of prominent foreground/midground objects.",
  }),
  photographic_characteristics: z
    .union([zPhotographicCharacteristicsDetails, z.unknown()])
    .optional(),
  aesthetics: zAestheticsDetails,
  lighting: zLightingDetails,
  context: z.string().register(z.globalRegistry, {
    description:
      "Provide any additional context that helps understand the image better.",
  }),
  short_description: z.string().register(z.globalRegistry, {
    description: "A concise summary of the image content, 200 words maximum.",
  }),
});

export const zFiboLiteGenerateStructuredPromptOutput = z.unknown();

/**
 * StructuredPromptInput
 */
export const zFiboLiteGenerateStructuredPromptInput = z.object({
  prompt: z.union([z.string(), z.unknown()]).optional(),
  seed: z
    .int()
    .register(z.globalRegistry, {
      description: "Seed for the random number generator.",
    })
    .optional()
    .default(7),
  structured_prompt: z.union([zStructuredPrompt, z.unknown()]).optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * File
 */
export const zFile = z.object({
  file_size: z.union([z.int(), z.unknown()]).optional(),
  file_name: z.union([z.string(), z.unknown()]).optional(),
  content_type: z.union([z.string(), z.unknown()]).optional(),
  url: z.string().register(z.globalRegistry, {
    description: "The URL where the file can be downloaded from.",
  }),
});

/**
 * LottieOutput
 */
export const zOmnilottieVideoToLottieOutput = z.object({
  lottie_file: zFile,
});

/**
 * VideoToLottieInput
 */
export const zOmnilottieVideoToLottieInput = z.object({
  prompt: z.union([z.string(), z.unknown()]).optional(),
  video_url: z.union([z.string(), z.string()]),
  top_p: z
    .number()
    .gte(0)
    .lte(1)
    .register(z.globalRegistry, {
      description: "Nucleus sampling probability threshold.",
    })
    .optional()
    .default(0.25),
  max_tokens: z
    .int()
    .gte(256)
    .lte(8192)
    .register(z.globalRegistry, {
      description: "Maximum number of Lottie tokens to generate.",
    })
    .optional()
    .default(4096),
  temperature: z
    .number()
    .gte(0)
    .lte(2)
    .register(z.globalRegistry, {
      description: "Sampling temperature for generation.",
    })
    .optional()
    .default(0.9),
  top_k: z
    .int()
    .gte(1)
    .lte(100)
    .register(z.globalRegistry, {
      description: "Top-k sampling parameter.",
    })
    .optional()
    .default(5),
});

/**
 * WaveformOutput
 */
export const zFfmpegApiWaveformOutput = z.object({
  waveform: z.array(z.number()).register(z.globalRegistry, {
    description:
      "Normalized waveform data as an array of values between -1 and 1. The number of points is determined by audio duration × points_per_second.",
  }),
  duration: z.number().register(z.globalRegistry, {
    description: "Duration of the audio in seconds",
  }),
  points: z.int().register(z.globalRegistry, {
    description: "Number of points in the waveform data",
  }),
  precision: z.int().register(z.globalRegistry, {
    description: "Number of decimal places used in the waveform values",
  }),
});

/**
 * WaveformInput
 */
export const zFfmpegApiWaveformInput = z.object({
  points_per_second: z
    .number()
    .gte(1)
    .lte(10)
    .register(z.globalRegistry, {
      description:
        "Controls how many points are sampled per second of audio. Lower values (e.g. 1-2) create a coarser waveform, higher values (e.g. 4-10) create a more detailed one.",
    })
    .optional()
    .default(4),
  smoothing_window: z
    .int()
    .gte(1)
    .lte(21)
    .register(z.globalRegistry, {
      description:
        "Size of the smoothing window. Higher values create a smoother waveform. Must be an odd number.",
    })
    .optional()
    .default(3),
  media_url: z.union([z.string(), z.string()]),
  precision: z
    .int()
    .gte(1)
    .lte(6)
    .register(z.globalRegistry, {
      description:
        "Number of decimal places for the waveform values. Higher values provide more precision but increase payload size.",
    })
    .optional()
    .default(2),
});

/**
 * LoudnormSummary
 */
export const zLoudnormSummary = z.object({
  output_integrated: z.union([z.number(), z.unknown()]).optional(),
  output_lra: z.union([z.number(), z.unknown()]).optional(),
  input_lra: z.union([z.number(), z.unknown()]).optional(),
  normalization_type: z.union([z.string(), z.unknown()]).optional(),
  output_true_peak: z.union([z.number(), z.unknown()]).optional(),
  target_offset: z.union([z.number(), z.unknown()]).optional(),
  input_integrated: z.union([z.number(), z.unknown()]).optional(),
  input_true_peak: z.union([z.number(), z.unknown()]).optional(),
  output_threshold: z.union([z.number(), z.unknown()]).optional(),
  input_threshold: z.union([z.number(), z.unknown()]).optional(),
});

/**
 * LoudnormOutput
 */
export const zFfmpegApiLoudnormOutput = z.object({
  summary: z.union([zLoudnormSummary, z.unknown()]).optional(),
  audio: zFile,
});

/**
 * LoudnormInput
 */
export const zFfmpegApiLoudnormInput = z.object({
  measured_lra: z.union([z.number().gte(0).lte(99), z.unknown()]).optional(),
  print_summary: z
    .boolean()
    .register(z.globalRegistry, {
      description:
        "Return loudness measurement summary with the normalized audio",
    })
    .optional()
    .default(false),
  offset: z
    .number()
    .gte(-99)
    .lte(99)
    .register(z.globalRegistry, {
      description: "Offset gain in dB applied before the true-peak limiter",
    })
    .optional()
    .default(0),
  measured_i: z.union([z.number().gte(-99).lte(0), z.unknown()]).optional(),
  measured_tp: z.union([z.number().gte(-99).lte(99), z.unknown()]).optional(),
  linear: z
    .boolean()
    .register(z.globalRegistry, {
      description:
        "Use linear normalization mode (single-pass). If false, uses dynamic mode (two-pass for better quality).",
    })
    .optional()
    .default(false),
  dual_mono: z
    .boolean()
    .register(z.globalRegistry, {
      description:
        "Treat mono input files as dual-mono for correct EBU R128 measurement on stereo systems",
    })
    .optional()
    .default(false),
  measured_thresh: z
    .union([z.number().gte(-99).lte(0), z.unknown()])
    .optional(),
  true_peak: z
    .number()
    .gte(-9)
    .lte(0)
    .register(z.globalRegistry, {
      description: "Maximum true peak in dBTP.",
    })
    .optional()
    .default(-0.1),
  audio_url: z.union([z.string(), z.string()]),
  integrated_loudness: z
    .number()
    .gte(-70)
    .lte(-5)
    .register(z.globalRegistry, {
      description: "Integrated loudness target in LUFS.",
    })
    .optional()
    .default(-18),
  loudness_range: z
    .number()
    .gte(1)
    .lte(20)
    .register(z.globalRegistry, {
      description: "Loudness range target in LU",
    })
    .optional()
    .default(7),
});

/**
 * LottieOutput
 */
export const zOmnilottieOutput = z.object({
  lottie_file: zFile,
});

/**
 * TextToLottieInput
 */
export const zOmnilottieInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Text description of the Lottie animation to generate.",
  }),
  top_p: z
    .number()
    .gte(0)
    .lte(1)
    .register(z.globalRegistry, {
      description: "Nucleus sampling probability threshold.",
    })
    .optional()
    .default(0.25),
  max_tokens: z
    .int()
    .gte(256)
    .lte(8192)
    .register(z.globalRegistry, {
      description: "Maximum number of Lottie tokens to generate.",
    })
    .optional()
    .default(4096),
  temperature: z
    .number()
    .gte(0)
    .lte(2)
    .register(z.globalRegistry, {
      description: "Sampling temperature for generation.",
    })
    .optional()
    .default(0.9),
  top_k: z
    .int()
    .gte(1)
    .lte(100)
    .register(z.globalRegistry, {
      description: "Top-k sampling parameter.",
    })
    .optional()
    .default(5),
});

/**
 * LottieOutput
 */
export const zOmnilottieImageToLottieOutput = z.object({
  lottie_file: zFile,
});

/**
 * ImageToLottieInput
 */
export const zOmnilottieImageToLottieInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Text description guiding the animation of the image.",
  }),
  image_url: z.union([z.string(), z.string()]),
  top_p: z
    .number()
    .gte(0)
    .lte(1)
    .register(z.globalRegistry, {
      description: "Nucleus sampling probability threshold.",
    })
    .optional()
    .default(0.25),
  max_tokens: z
    .int()
    .gte(256)
    .lte(8192)
    .register(z.globalRegistry, {
      description: "Maximum number of Lottie tokens to generate.",
    })
    .optional()
    .default(4096),
  temperature: z
    .number()
    .gte(0)
    .lte(2)
    .register(z.globalRegistry, {
      description: "Sampling temperature for generation.",
    })
    .optional()
    .default(0.9),
  top_k: z
    .int()
    .gte(1)
    .lte(100)
    .register(z.globalRegistry, {
      description: "Top-k sampling parameter.",
    })
    .optional()
    .default(5),
});

/**
 * AudioTrack
 */
export const zAudioTrack = z.object({
  codec: z.string().register(z.globalRegistry, {
    description: "Audio codec used (e.g., 'aac', 'mp3')",
  }),
  bitrate: z.int().register(z.globalRegistry, {
    description: "Audio bitrate in bits per second",
  }),
  sample_rate: z.int().register(z.globalRegistry, {
    description: "Audio sample rate in Hz",
  }),
  channels: z.int().register(z.globalRegistry, {
    description: "Number of audio channels",
  }),
});

/**
 * Resolution
 */
export const zResolution = z.object({
  height: z.int().register(z.globalRegistry, {
    description: "Height of the video in pixels",
  }),
  aspect_ratio: z.string().register(z.globalRegistry, {
    description: "Display aspect ratio (e.g., '16:9')",
  }),
  width: z.int().register(z.globalRegistry, {
    description: "Width of the video in pixels",
  }),
});

/**
 * VideoFormat
 */
export const zVideoFormat = z.object({
  profile: z.string().register(z.globalRegistry, {
    description: "Codec profile (e.g., 'main', 'high')",
  }),
  level: z.number().register(z.globalRegistry, {
    description: "Codec level (e.g., 4.1)",
  }),
  pixel_format: z.string().register(z.globalRegistry, {
    description: "Pixel format used (e.g., 'yuv420p')",
  }),
  video_codec: z.string().register(z.globalRegistry, {
    description: "Video codec used (e.g., 'h264')",
  }),
  container: z.string().register(z.globalRegistry, {
    description: "Container format of the video",
  }),
  bitrate: z.int().register(z.globalRegistry, {
    description: "Video bitrate in bits per second",
  }),
});

/**
 * Audio
 */
export const zAudio = z.object({
  file_size: z.int().register(z.globalRegistry, {
    description: "Size of the file in bytes",
  }),
  duration: z.number().register(z.globalRegistry, {
    description: "Duration of the media in seconds",
  }),
  channels: z.int().register(z.globalRegistry, {
    description: "Number of audio channels",
  }),
  url: z.string().register(z.globalRegistry, {
    description: "URL where the media file can be accessed",
  }),
  media_type: z
    .string()
    .register(z.globalRegistry, {
      description: "Type of media (always 'audio')",
    })
    .optional()
    .default("audio"),
  codec: z.string().register(z.globalRegistry, {
    description: "Codec used to encode the media",
  }),
  file_name: z.string().register(z.globalRegistry, {
    description: "Original filename of the media",
  }),
  sample_rate: z.int().register(z.globalRegistry, {
    description: "Audio sample rate in Hz",
  }),
  content_type: z.string().register(z.globalRegistry, {
    description: "MIME type of the media file",
  }),
  container: z.string().register(z.globalRegistry, {
    description: "Container format of the media file (e.g., 'mp4', 'mov')",
  }),
  bitrate: z.int().register(z.globalRegistry, {
    description: "Overall bitrate of the media in bits per second",
  }),
});

/**
 * Video
 */
export const zVideo = z.object({
  file_size: z.int().register(z.globalRegistry, {
    description: "Size of the file in bytes",
  }),
  timebase: z.string().register(z.globalRegistry, {
    description: "Time base used for frame timestamps",
  }),
  start_frame_url: z.union([z.string(), z.unknown()]).optional(),
  duration: z.number().register(z.globalRegistry, {
    description: "Duration of the media in seconds",
  }),
  url: z.string().register(z.globalRegistry, {
    description: "URL where the media file can be accessed",
  }),
  media_type: z
    .string()
    .register(z.globalRegistry, {
      description: "Type of media (always 'video')",
    })
    .optional()
    .default("video"),
  codec: z.string().register(z.globalRegistry, {
    description: "Codec used to encode the media",
  }),
  fps: z.int().register(z.globalRegistry, {
    description: "Frames per second",
  }),
  end_frame_url: z.union([z.string(), z.unknown()]).optional(),
  content_type: z.string().register(z.globalRegistry, {
    description: "MIME type of the media file",
  }),
  container: z.string().register(z.globalRegistry, {
    description: "Container format of the media file (e.g., 'mp4', 'mov')",
  }),
  bitrate: z.int().register(z.globalRegistry, {
    description: "Overall bitrate of the media in bits per second",
  }),
  format: zVideoFormat,
  resolution: zResolution,
  frame_count: z.int().register(z.globalRegistry, {
    description: "Total number of frames in the video",
  }),
  file_name: z.string().register(z.globalRegistry, {
    description: "Original filename of the media",
  }),
  audio: z.union([zAudioTrack, z.unknown()]).optional(),
});

/**
 * MetadataOutput
 */
export const zFfmpegApiMetadataOutput = z.object({
  media: z.union([zVideo, zAudio]),
});

/**
 * MetadataInput
 */
export const zFfmpegApiMetadataInput = z.object({
  extract_frames: z
    .boolean()
    .register(z.globalRegistry, {
      description:
        "Whether to extract the start and end frames for videos. Note that when true the request will be slower.",
    })
    .optional()
    .default(false),
  media_url: z.union([z.string(), z.string()]),
});

/**
 * TextOutput
 */
export const zBagelUnderstandOutput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "The query used for the generation.",
  }),
  text: z.string().register(z.globalRegistry, {
    description: "The answer to the query.",
  }),
  timings: z.record(z.string(), z.unknown()).register(z.globalRegistry, {
    description: "The timings of the generation.",
  }),
  seed: z.int().register(z.globalRegistry, {
    description: "The seed used for the generation.",
  }),
});

/**
 * ImageUnderstandingInput
 */
export const zBagelUnderstandInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "The prompt to query the image with.",
  }),
  seed: z
    .int()
    .register(z.globalRegistry, {
      description: "The seed to use for the generation.",
    })
    .optional(),
  image_url: z.union([z.string(), z.string()]),
});

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string().register(z.globalRegistry, {
    description: "The request id.",
  }),
  response_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The response url.",
    })
    .optional(),
  status_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The status url.",
    })
    .optional(),
  cancel_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The cancel url.",
    })
    .optional(),
  logs: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The logs.",
    })
    .optional(),
  metrics: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The metrics.",
    })
    .optional(),
  queue_position: z
    .int()
    .register(z.globalRegistry, {
      description: "The queue position.",
    })
    .optional(),
});

export const zGetFalAiBagelUnderstandRequestsByRequestIdStatusData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z
    .object({
      logs: z
        .number()
        .register(z.globalRegistry, {
          description:
            "Whether to include logs (`1`) in the response or not (`0`).",
        })
        .optional(),
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiBagelUnderstandRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiBagelUnderstandRequestsByRequestIdCancelData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiBagelUnderstandRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiBagelUnderstandData = z.object({
  body: zBagelUnderstandInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiBagelUnderstandResponse = zQueueStatus;

export const zGetFalAiBagelUnderstandRequestsByRequestIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * Result of the request.
 */
export const zGetFalAiBagelUnderstandRequestsByRequestIdResponse =
  zBagelUnderstandOutput;

export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdStatusData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  },
);

/**
 * The request status.
 */
export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiFfmpegApiMetadataRequestsByRequestIdCancelData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  },
);

/**
 * The request was cancelled.
 */
export const zPutFalAiFfmpegApiMetadataRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiFfmpegApiMetadataData = z.object({
  body: zFfmpegApiMetadataInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiFfmpegApiMetadataResponse = zQueueStatus;

export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * Result of the request.
 */
export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdResponse =
  zFfmpegApiMetadataOutput;

export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostFalAiOmnilottieImageToLottieData = z.object({
  body: zOmnilottieImageToLottieInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiOmnilottieImageToLottieResponse = zQueueStatus;

export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  },
);

/**
 * Result of the request.
 */
export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdResponse =
  zOmnilottieImageToLottieOutput;

export const zGetFalAiOmnilottieRequestsByRequestIdStatusData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z
    .object({
      logs: z
        .number()
        .register(z.globalRegistry, {
          description:
            "Whether to include logs (`1`) in the response or not (`0`).",
        })
        .optional(),
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiOmnilottieRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiOmnilottieRequestsByRequestIdCancelData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiOmnilottieRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiOmnilottieData = z.object({
  body: zOmnilottieInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiOmnilottieResponse = zQueueStatus;

export const zGetFalAiOmnilottieRequestsByRequestIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * Result of the request.
 */
export const zGetFalAiOmnilottieRequestsByRequestIdResponse = zOmnilottieOutput;

export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  },
);

/**
 * The request status.
 */
export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  },
);

/**
 * The request was cancelled.
 */
export const zPutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiFfmpegApiLoudnormData = z.object({
  body: zFfmpegApiLoudnormInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiFfmpegApiLoudnormResponse = zQueueStatus;

export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * Result of the request.
 */
export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdResponse =
  zFfmpegApiLoudnormOutput;

export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdStatusData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  },
);

/**
 * The request status.
 */
export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiFfmpegApiWaveformRequestsByRequestIdCancelData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  },
);

/**
 * The request was cancelled.
 */
export const zPutFalAiFfmpegApiWaveformRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiFfmpegApiWaveformData = z.object({
  body: zFfmpegApiWaveformInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiFfmpegApiWaveformResponse = zQueueStatus;

export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.never().optional(),
});

/**
 * Result of the request.
 */
export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdResponse =
  zFfmpegApiWaveformOutput;

export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostFalAiOmnilottieVideoToLottieData = z.object({
  body: zOmnilottieVideoToLottieInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostFalAiOmnilottieVideoToLottieResponse = zQueueStatus;

export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdData = z.object(
  {
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  },
);

/**
 * Result of the request.
 */
export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdResponse =
  zOmnilottieVideoToLottieOutput;

export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * The request was cancelled.
 */
export const zPutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostBriaFiboLiteGenerateStructuredPromptData = z.object({
  body: zFiboLiteGenerateStructuredPromptInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostBriaFiboLiteGenerateStructuredPromptResponse = zQueueStatus;

export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * Result of the request.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdResponse =
  zFiboLiteGenerateStructuredPromptOutput;

export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * The request was cancelled.
 */
export const zPutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostBriaFiboGenerateStructuredPromptData = z.object({
  body: zFiboGenerateStructuredPromptInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostBriaFiboGenerateStructuredPromptResponse = zQueueStatus;

export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * Result of the request.
 */
export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdResponse =
  zFiboGenerateStructuredPromptOutput;

export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * The request was cancelled.
 */
export const zPutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostBriaFiboEditEditStructuredInstructionData = z.object({
  body: zFiboEditEditStructuredInstructionInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostBriaFiboEditEditStructuredInstructionResponse = zQueueStatus;

export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * Result of the request.
 */
export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdResponse =
  zFiboEditEditStructuredInstructionOutput;

export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z
      .object({
        logs: z
          .number()
          .register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          })
          .optional(),
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * The request was cancelled.
 */
export const zPutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostBriaFiboLiteGenerateStructuredPromptLiteData = z.object({
  body: zFiboLiteGenerateStructuredPromptLiteInput,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * The request status.
 */
export const zPostBriaFiboLiteGenerateStructuredPromptLiteResponse =
  zQueueStatus;

export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdData =
  z.object({
    body: z.never().optional(),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.never().optional(),
  });

/**
 * Result of the request.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdResponse =
  zFiboLiteGenerateStructuredPromptLiteOutput;
