// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://queue.fal.run" | (string & {});
};

/**
 * File
 */
export type File = {
  /**
   * File Size
   *
   * The size of the file in bytes.
   */
  file_size?: number | unknown;
  /**
   * File Name
   *
   * The name of the file. It will be auto-generated if not provided.
   */
  file_name?: string | unknown;
  /**
   * Content Type
   *
   * The mime type of the file.
   */
  content_type?: string | unknown;
  /**
   * Url
   *
   * The URL where the file can be downloaded from.
   */
  url: string;
};

/**
 * InterleaveVideoOutput
 *
 * Output model for interleaved video
 */
export type WorkflowUtilitiesInterleaveVideoOutput = {
  video: File;
};

/**
 * InterleaveVideoInput
 *
 * Input model for interleaving multiple videos
 */
export type WorkflowUtilitiesInterleaveVideoInput = {
  /**
   * Video Urls
   *
   * List of video URLs to interleave in order
   */
  video_urls: Array<string>;
};

/**
 * UsageInfo
 */
export type UsageInfo = {
  /**
   * Completion Tokens
   */
  completion_tokens?: number | unknown;
  /**
   * Total Tokens
   */
  total_tokens?: number;
  /**
   * Prompt Tokens
   */
  prompt_tokens?: number | unknown;
  /**
   * Cost
   */
  cost: number;
};

/**
 * AudioOutput
 */
export type RouterAudioOutput = {
  /**
   * Token usage information
   */
  usage: UsageInfo | unknown;
  /**
   * Output
   *
   * Generated output from audio processing
   */
  output: string;
};

/**
 * AudioInput
 */
export type RouterAudioInput = {
  /**
   * Prompt
   *
   * Prompt to be used for the audio processing
   */
  prompt: string;
  /**
   * System Prompt
   *
   * System prompt to provide context or instructions to the model
   */
  system_prompt?: string | unknown;
  /**
   * Reasoning
   *
   * Should reasoning be the part of the final answer.
   */
  reasoning?: boolean;
  /**
   * Model
   *
   * Name of the model to use. Charged based on actual token usage.
   */
  model: string;
  /**
   * Audio Url
   *
   * URL or data URI of the audio file to process. Supported formats: wav, mp3, aiff, aac, ogg, flac, m4a.
   */
  audio_url: string;
  /**
   * Temperature
   *
   * This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.
   */
  temperature?: number;
  /**
   * Max Tokens
   *
   * This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.
   */
  max_tokens?: number | unknown;
};

export type QueueStatus = {
  status: "IN_QUEUE" | "IN_PROGRESS" | "COMPLETED";
  /**
   * The request id.
   */
  request_id: string;
  /**
   * The response url.
   */
  response_url?: string;
  /**
   * The status url.
   */
  status_url?: string;
  /**
   * The cancel url.
   */
  cancel_url?: string;
  /**
   * The logs.
   */
  logs?: {
    [key: string]: unknown;
  };
  /**
   * The metrics.
   */
  metrics?: {
    [key: string]: unknown;
  };
  /**
   * The queue position.
   */
  queue_position?: number;
};

export type GetOpenrouterRouterAudioRequestsByRequestIdStatusData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: {
    /**
     * Whether to include logs (`1`) in the response or not (`0`).
     */
    logs?: number;
  };
  url: "/openrouter/router/audio/requests/{request_id}/status";
};

export type GetOpenrouterRouterAudioRequestsByRequestIdStatusResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type GetOpenrouterRouterAudioRequestsByRequestIdStatusResponse =
  GetOpenrouterRouterAudioRequestsByRequestIdStatusResponses[keyof GetOpenrouterRouterAudioRequestsByRequestIdStatusResponses];

export type PutOpenrouterRouterAudioRequestsByRequestIdCancelData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/openrouter/router/audio/requests/{request_id}/cancel";
};

export type PutOpenrouterRouterAudioRequestsByRequestIdCancelResponses = {
  /**
   * The request was cancelled.
   */
  200: {
    /**
     * Whether the request was cancelled successfully.
     */
    success?: boolean;
  };
};

export type PutOpenrouterRouterAudioRequestsByRequestIdCancelResponse =
  PutOpenrouterRouterAudioRequestsByRequestIdCancelResponses[keyof PutOpenrouterRouterAudioRequestsByRequestIdCancelResponses];

export type PostOpenrouterRouterAudioData = {
  body: RouterAudioInput;
  path?: never;
  query?: never;
  url: "/openrouter/router/audio";
};

export type PostOpenrouterRouterAudioResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostOpenrouterRouterAudioResponse =
  PostOpenrouterRouterAudioResponses[keyof PostOpenrouterRouterAudioResponses];

export type GetOpenrouterRouterAudioRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/openrouter/router/audio/requests/{request_id}";
};

export type GetOpenrouterRouterAudioRequestsByRequestIdResponses = {
  /**
   * Result of the request.
   */
  200: RouterAudioOutput;
};

export type GetOpenrouterRouterAudioRequestsByRequestIdResponse =
  GetOpenrouterRouterAudioRequestsByRequestIdResponses[keyof GetOpenrouterRouterAudioRequestsByRequestIdResponses];

export type GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: {
      /**
       * Whether to include logs (`1`) in the response or not (`0`).
       */
      logs?: number;
    };
    url: "/fal-ai/workflow-utilities/interleave-video/requests/{request_id}/status";
  };

export type GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusResponses =
  {
    /**
     * The request status.
     */
    200: QueueStatus;
  };

export type GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusResponse =
  GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusResponses[keyof GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusResponses];

export type PutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelData =
  {
    body?: never;
    path: {
      /**
       * Request ID
       */
      request_id: string;
    };
    query?: never;
    url: "/fal-ai/workflow-utilities/interleave-video/requests/{request_id}/cancel";
  };

export type PutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelResponses =
  {
    /**
     * The request was cancelled.
     */
    200: {
      /**
       * Whether the request was cancelled successfully.
       */
      success?: boolean;
    };
  };

export type PutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelResponse =
  PutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelResponses[keyof PutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelResponses];

export type PostFalAiWorkflowUtilitiesInterleaveVideoData = {
  body: WorkflowUtilitiesInterleaveVideoInput;
  path?: never;
  query?: never;
  url: "/fal-ai/workflow-utilities/interleave-video";
};

export type PostFalAiWorkflowUtilitiesInterleaveVideoResponses = {
  /**
   * The request status.
   */
  200: QueueStatus;
};

export type PostFalAiWorkflowUtilitiesInterleaveVideoResponse =
  PostFalAiWorkflowUtilitiesInterleaveVideoResponses[keyof PostFalAiWorkflowUtilitiesInterleaveVideoResponses];

export type GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdData = {
  body?: never;
  path: {
    /**
     * Request ID
     */
    request_id: string;
  };
  query?: never;
  url: "/fal-ai/workflow-utilities/interleave-video/requests/{request_id}";
};

export type GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdResponses =
  {
    /**
     * Result of the request.
     */
    200: WorkflowUtilitiesInterleaveVideoOutput;
  };

export type GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdResponse =
  GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdResponses[keyof GetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdResponses];
