// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * File
 */
export const zFile = z.object({
  file_size: z.optional(z.union([z.int(), z.unknown()])),
  file_name: z.optional(z.union([z.string(), z.unknown()])),
  content_type: z.optional(z.union([z.string(), z.unknown()])),
  url: z.string().register(z.globalRegistry, {
    description: "The URL where the file can be downloaded from.",
  }),
});

/**
 * InterleaveVideoOutput
 *
 * Output model for interleaved video
 */
export const zWorkflowUtilitiesInterleaveVideoOutput = z
  .object({
    video: zFile,
  })
  .register(z.globalRegistry, {
    description: "Output model for interleaved video",
  });

/**
 * InterleaveVideoInput
 *
 * Input model for interleaving multiple videos
 */
export const zWorkflowUtilitiesInterleaveVideoInput = z
  .object({
    video_urls: z.array(z.string()).register(z.globalRegistry, {
      description: "List of video URLs to interleave in order",
    }),
  })
  .register(z.globalRegistry, {
    description: "Input model for interleaving multiple videos",
  });

/**
 * UsageInfo
 */
export const zUsageInfo = z.object({
  completion_tokens: z.optional(z.union([z.int(), z.unknown()])),
  total_tokens: z.optional(z.int()).default(0),
  prompt_tokens: z.optional(z.union([z.int(), z.unknown()])),
  cost: z.number(),
});

/**
 * AudioOutput
 */
export const zRouterAudioOutput = z.object({
  usage: z.union([zUsageInfo, z.unknown()]),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output from audio processing",
  }),
});

/**
 * AudioInput
 */
export const zRouterAudioInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the audio processing",
  }),
  system_prompt: z.optional(z.union([z.string(), z.unknown()])),
  reasoning: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: "Should reasoning be the part of the final answer.",
      }),
    )
    .default(false),
  model: z.string().register(z.globalRegistry, {
    description:
      "Name of the model to use. Charged based on actual token usage.",
  }),
  audio_url: z.union([z.string(), z.string()]),
  temperature: z
    .optional(
      z.number().gte(0).lte(2).register(z.globalRegistry, {
        description:
          "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
      }),
    )
    .default(1),
  max_tokens: z.optional(z.union([z.int().gte(1), z.unknown()])),
});

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string().register(z.globalRegistry, {
    description: "The request id.",
  }),
  response_url: z.optional(
    z.string().register(z.globalRegistry, {
      description: "The response url.",
    }),
  ),
  status_url: z.optional(
    z.string().register(z.globalRegistry, {
      description: "The status url.",
    }),
  ),
  cancel_url: z.optional(
    z.string().register(z.globalRegistry, {
      description: "The cancel url.",
    }),
  ),
  logs: z.optional(
    z.record(z.string(), z.unknown()).register(z.globalRegistry, {
      description: "The logs.",
    }),
  ),
  metrics: z.optional(
    z.record(z.string(), z.unknown()).register(z.globalRegistry, {
      description: "The metrics.",
    }),
  ),
  queue_position: z.optional(
    z.int().register(z.globalRegistry, {
      description: "The queue position.",
    }),
  ),
});

export const zGetOpenrouterRouterAudioRequestsByRequestIdStatusData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(
    z.object({
      logs: z.optional(
        z.number().register(z.globalRegistry, {
          description:
            "Whether to include logs (`1`) in the response or not (`0`).",
        }),
      ),
    }),
  ),
});

/**
 * The request status.
 */
export const zGetOpenrouterRouterAudioRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutOpenrouterRouterAudioRequestsByRequestIdCancelData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterAudioRequestsByRequestIdCancelResponse = z
  .object({
    success: z.optional(
      z.boolean().register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      }),
    ),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostOpenrouterRouterAudioData = z.object({
  body: zRouterAudioInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostOpenrouterRouterAudioResponse = zQueueStatus;

export const zGetOpenrouterRouterAudioRequestsByRequestIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterAudioRequestsByRequestIdResponse =
  zRouterAudioOutput;

export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(
      z.object({
        logs: z.optional(
          z.number().register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          }),
        ),
      }),
    ),
  });

/**
 * The request status.
 */
export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z.optional(
        z.boolean().register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        }),
      ),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostFalAiWorkflowUtilitiesInterleaveVideoData = z.object({
  body: zWorkflowUtilitiesInterleaveVideoInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostFalAiWorkflowUtilitiesInterleaveVideoResponse = zQueueStatus;

export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * Result of the request.
 */
export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdResponse =
  zWorkflowUtilitiesInterleaveVideoOutput;
